### ISSUE TITLE
Remove the changes favorite/* files from this branch.  Keep this PR to only the assignment2 requirements.

### ISSUE THREAD

**Issue by blakestanger** [sleddog/methods-spring-2020#98]
Ok I tried to do this again with this one. @sleddog Did I do this correctly? 

Remove the changes favorite/* files from this branch.  Keep this PR to only the assignment2 requirements.
Rename the README.txt to README.md
And resolve merge conflicts.

_Originally posted by @sleddog in https://github.com/sleddog/methods-spring-2020/pull/59#issuecomment-590673148_

**Comment by sleddog** [comment]
looks resolved... closing
